# Site settings
title: Marco Scarpelli
description: 'Business Card Page'
url: ''
baseurl: ''
profilepic: '/images/marcoscarpelli.jpg'
bkimage: '/images/bk1.jpg'
google_analytics:
font_awesome: 'f12afb976f.js'

author:
  name: 'Marco Scarpelli'
  email: marcoscarpelli05@gmail.com
  github_username: Marco71915
  linkedin_username: marco-scarpelli-117207358
  instagram_username: _marcoscarpelli_
  telegram_username: ssmm_50

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']

